"""add content_blob to file_asset

Revision ID: 3c743678b730
Revises: ecb3070ee193
Create Date: 2026-01-14 17:11:37.347847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c743678b730'
down_revision = 'ecb3070ee193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_blob', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_asset', schema=None) as batch_op:
        batch_op.drop_column('content_blob')

    # ### end Alembic commands ###
